# 重回帰分析の実装

# 行列演算の基礎

# $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [17]:
import numpy as np

#ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

print()

#行列の定義
X = np.array([[1, 2], [3, 4]])
print(X)

print()

#転置
Xt = X.T
print(Xt)

print()

#逆行列
#Linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)


#行列積
XX_inv = np.dot(X,X_inv)
print()

print(XX_inv)

[[1]
 [2]
 [3]]

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い


In [25]:
x = np.array([1, 2, 3])
print(x.T) #これだと転置しない
print(type(x))


x = np.array([[1, 2, 3]])
print(x.T)

[1 2 3]
<class 'numpy.ndarray'>
[[1]
 [2]
 [3]]


# Numpyでよく使う機能

In [32]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]
])

print(X.shape) #行数と列数がわかる

row, col = X.shape
print(row)
print(col)
print()
for x in X:
    print(x)
    print('-----')

(2, 3)
2
3

[2 3 4]
-----
[1 2 3]
-----


# 演習問題

 $\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$のとき
$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- Step1: $\boldsymbol{X}^{T}\boldsymbol{X} $
- Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [36]:
import numpy as np 
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])

y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(X)
print(y)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]
[[1]
 [5]
 [6]
 [8]]


In [48]:
#Step1
Xt_X = np.dot(X.T,X)
print(Xt_X)

print('--------------------')
#Step2
Xt_X_inv = np.linalg.inv(Xt_X)
print(Xt_X_inv)

print('--------------------')
#Step3
Xt_y = np.dot(X.T,y)
print(Xt_y)

print('--------------------')
#Step4
w = np.dot(Xt_X_inv, Xt_y)
print(w)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]
--------------------
[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]
--------------------
[[ 20]
 [ 70]
 [124]]
--------------------
[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [50]:
import sklearn

In [58]:
#重回帰分析飲み読み込み
from sklearn.linear_model import LinearRegression

#モデルの宣言
model = LinearRegression()

# model = LinearRegression(fit_intercept=False)


#モデルの学習　<-- パラメータの調整
model.fit(X,y)

#m調整後のパラメータ
print(model.coef_)


print(model.intercept_)

[[0.         0.71428571 0.57142857]]
[-0.14285714]


In [59]:
# 予測精度　＜ーー決定係数
model.score(X,y)

0.6923076923076923

In [62]:
# 予測値の計算
x = np.array([[1, 2, 3]])

model.predict(x)
y_pred = model.predict(x)
print(y_pred)

[[3.]]
